INSERT INTO CULINARIA (NOME) VALUES ('Brasileira');
INSERT INTO CULINARIA (NOME) VALUES ('Japonesa');
INSERT INTO CULINARIA (NOME) VALUES ('Chinesa');

INSERT INTO RESTAURANTE (id, NOME, TAXA_FRETE, CULINARIA_ID) VALUES (1, 'Espaço Gourmet', 10, 1);
INSERT INTO RESTAURANTE (id, NOME, TAXA_FRETE, CULINARIA_ID) VALUES (2, 'Sushi do Mestre', 9.50, 3);
INSERT INTO RESTAURANTE (id, NOME, TAXA_FRETE, CULINARIA_ID) VALUES (3, 'Careca', 15, 3);

INSERT INTO ESTADO (id, NOME) VALUES (1, 'Minas Gerais');
INSERT INTO ESTADO (id, NOME) VALUES (2, 'São Paulo');
INSERT INTO ESTADO (id, NOME) VALUES (3, 'Distrito Federal');

INSERT INTO CIDADE (id, NOME, ESTADO_ID) VALUES (1, 'Uberlândia', 1);
INSERT INTO CIDADE (id, NOME, ESTADO_ID) VALUES (2, 'Belo Horizonte', 1);
INSERT INTO CIDADE (id, NOME, ESTADO_ID) VALUES (3, 'São Paulo', 2);
INSERT INTO CIDADE (id, NOME, ESTADO_ID) VALUES (4, 'Campinas', 2);
INSERT INTO CIDADE (id, NOME, ESTADO_ID) VALUES (5, 'Brasília', 3);