INSERT INTO CULINARIA (NOME) VALUES ('Brasileira');
INSERT INTO CULINARIA (NOME) VALUES ('Japonesa');
INSERT INTO CULINARIA (NOME) VALUES ('Chinesa');

INSERT INTO RESTAURANTE (id, NOME, TAXA_FRETE, CULINARIA_ID) VALUES (1, 'Espaço Gourmet', 10, 1);
INSERT INTO RESTAURANTE (id, NOME, TAXA_FRETE, CULINARIA_ID) VALUES (2, 'Sushi do Mestre', 9.50, 3);
INSERT INTO RESTAURANTE (id, NOME, TAXA_FRETE, CULINARIA_ID) VALUES (3, 'Careca', 15, 3);